name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  builds:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run a one line script
        run: echo Hello world!
   
   
  

  
 


















