name: CI #Indentation is very much important in .yml file because if file have indentation errors then it will fail.

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  builds:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run a one line script
        run: echo Hello world!
      - name: run multiline script
        run: |
            echo adding other atctions
            echo test and deploy
   
   
  

  
 


















